; keep your global constant values inside this file



; ram_btn_hold
; ram_btn_press
con_btn_Right                           = $01 ; 
con_btn_Left                            = $02 ; 
con_btn_Down                            = $04 ; 
con_btn_Up                              = $08 ; 
con_btn_Start                           = $10 ; 
con_btn_Select                          = $20 ; 
con_btn_B                               = $40 ; 
con_btn_A                               = $80 ; 



; ram_mario_message
con_msg_in                              = $00 ; in
con_msg_out                             = $01 ; out
con_msg_net                             = $02 ; net
con_msg_fault                           = $03 ; fault
con_msg_double_fault                    = $04 ; double_fault
con_msg_deuce                           = $05 ; deuce



