; keep your global constant values inside this file



; MISC
con_ofs_obj                             = $00 ; object offset, for easier searching
; con_ofs_plr                           = $00 ; player offset, for easier searching



; ram_obj_1_data
; ram_obj_2_data
; ram_obj_3_data
con_obj_pos_X_lo                        = $00 ; 
con_obj_pos_X_hi                        = $01 ; 
con_obj_pos_Y_lo                        = $02 ; 
con_obj_pos_Y_hi                        = $03 ; 
con_obj_animation                       = $04 ; 
con_obj_05                              = $05 ; 
con_obj_direction                       = $06 ; 
con_obj_07                              = $07 ; 
con_obj_08                              = $08 ; 
con_obj_09                              = $09 ; 
con_obj_0A                              = $0A ; 
con_obj_0B                              = $0B ; 
con_obj_0C                              = $0C ; 
con_obj_movement                        = $0D ; 
con_obj_0E                              = $0E ; 
con_obj_0F                              = $0F ; 



; ram_obj_1_animation
; ram_obj_2_animation
; need comments 0x000366
con_anim_id_00                          = $00 ; 
con_anim_id_02                          = $02 ; 
con_anim_id_04                          = $04 ; jumping
con_anim_id_06                          = $06 ; falling down
con_anim_id_08                          = $08 ; sound wave
con_anim_id_0A                          = $0A ; bell
con_anim_id_0C                          = $0C ; cat was stunned by opened door
con_anim_id_0E                          = $0E ; 
con_anim_id_10                          = $10 ; 
con_anim_id_12                          = $12 ; fat cat is hiding inside item
con_anim_id_14                          = $14 ; fat cat is showing 1000 points sign
con_anim_id_16                          = $16 ; 
con_anim_id_18                          = $18 ; 
; con_anim_id_1A                        = $1A ; unused
con_anim_id_1C                          = $1C ; 
con_anim_id_1E                          = $1E ; 
con_anim_id_20                          = $20 ; 
con_anim_id_22                          = $22 ; 
con_anim_id_24                          = $24 ; 



; for 0x001546
con_D536_00                             = $00 ; 
con_D536_02                             = $02 ; 
con_D536_04                             = $04 ; 
con_D536_06                             = $06 ; 
con_D536_08                             = $08 ; 
con_D536_0A                             = $0A ; 
con_D536_0C                             = $0C ; 



; for 0x001650
con_D640_00                             = $00 ; 
; con_D640_02                           = $02 ; unused
con_D640_04                             = $04 ; 
; con_D640_06                           = $06 ; unused
con_D640_08                             = $08 ; 
con_D640_0A                             = $0A ; 
con_D640_0C                             = $0C ; 
con_D640_0E                             = $0E ; 
con_D640_10                             = $10 ; 
con_D640_12                             = $12 ; 
con_D640_14                             = $14 ; 
con_D640_16                             = $16 ; 



