; keep your global constant values inside this file



; for 0x001546
con_D536_00                                 = $00 ; 
con_D536_02                                 = $02 ; 
con_D536_04                                 = $04 ; 
con_D536_06                                 = $06 ; 
con_D536_08                                 = $08 ; 
con_D536_0A                                 = $0A ; 
con_D536_0C                                 = $0C ; 



; for 0x001650
con_D640_00                                 = $00 ; 
con_D640_02                                 = $02 ; 
con_D640_04                                 = $04 ; 
con_D640_06                                 = $06 ; 
con_D640_08                                 = $08 ; 
con_D640_0A                                 = $0A ; 
con_D640_0C                                 = $0C ; 
con_D640_0E                                 = $0E ; 
con_D640_10                                 = $10 ; 
con_D640_12                                 = $12 ; 
con_D640_14                                 = $14 ; 
con_D640_16                                 = $16 ; 



