; keep your global constant values inside this file

; todo
    ; доделать ADC/SBC 00



; MISC
con_prg_bank                            = $00 ; todo
con_gk_id                               = $0A ; goalkeeper
con_ball_id                             = $0C ; 



; control bytes 0x003069
con_B059_F0                             = $F0 ; 
con_B059_F1                             = $F1 ; 
con_B059_F2                             = $F2 ; 
con_B059_F3                             = $F3 ; 
con_B059_F4                             = $F4 ; 
con_B059_F5                             = $F5 ; 
con_B059_F6                             = $F6 ; 
con_B059_F7                             = $F7 ; 
con_B059_F8                             = $F8 ; 
con_B059_F9                             = $F9 ; 



; sound engine control bytes 0x00037E
con_se_cb_C0                            = $C0 ; 
con_se_cb_C1                            = $C1 ; 
con_se_cb_C2                            = $C2 ; 
con_se_cb_C3                            = $C3 ; 
con_se_cb_C4                            = $C4 ; 
con_se_cb_C5                            = $C5 ; 
; con_se_cb_C6                          = $C6 ; unused
con_se_cb_C7                            = $C7 ; 
; con_se_cb_C8                          = $C8 ; unused
con_se_cb_C9                            = $C9 ; 
con_se_cb_CA                            = $CA ; 
con_se_cb_CB                            = $CB ; 
con_se_cb_CC                            = $CC ; 
con_se_cb_CD                            = $CD ; 
con_se_cb_loop_1                        = $CE ; 
con_se_cb_loop_2                        = $CF ; 
con_se_cb_jmp                           = $D0 ; 
con_se_cb_jsr                           = $D1 ; 
con_se_cb_rts                           = $D2 ; 
con_se_cb_stop                          = $D3 ; 
con_se_cb_D4                            = $D4 ; 
; con_se_cb_D5                          = $D5 ; unused
; con_se_cb_D6                          = $D6 ; unused
; con_se_cb_D7                          = $D7 ; unused
con_se_cb_D8                            = $D8 ; 
; con_se_cb_D9                          = $D9 ; unused
con_se_cb_DA                            = $DA ; 
con_se_cb_DB                            = $DB ; 
; con_se_cb_DC                          = $DC ; unused
; con_se_cb_DD                          = $DD ; unused
con_se_cb_DE                            = $DE ; 
; con_se_cb_DF                          = $DF ; unused



