; keep your global constant values inside this file



; ram_btn_hold                          = $0005
; ram_btn_press                         = $0007
con_btn_Right                           = $01 ; 
con_btn_Left                            = $02 ; 
con_btn_Down                            = $04 ; 
con_btn_Up                              = $08 ; 
con_btn_Start                           = $10 ; 
con_btn_Select                          = $20 ; 
con_btn_B                               = $40 ; 
con_btn_A                               = $80 ; 



; ram_player_state                      = $009A
con_state_idle                          = $00 ; 
con_state_move_right                    = $01 ; 
con_state_move_left                     = $02 ; 
con_state_duck                          = $04 ; 
con_state_jump                          = $08 ; 
con_state_kick                          = $10 ; 
con_state_punch                         = $20 ; 